In [1]:
import cv2
import mediapipe as mp
import time
import pandas as pd


fm = mp.solutions.face_mesh
model = fm.FaceMesh(
    static_image_mode=False,
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.8,
    min_tracking_confidence=0.8,
)


vid = cv2.VideoCapture(0) 


regist = int(input("How many faces to register? "))
final_data = []

for y in range(regist):
    name = input(f"\nEnter name for person {y + 1}: ")
    print(f"\nCapturing 300 samples for '{name}' in 3 seconds...")
    time.sleep(3)

    sample_count = 0
    required_samples = 400

    while sample_count < required_samples:
        success, frame = vid.read()
        if not success:
            print("Camera error.")
            break

        
        frgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        output = model.process(frgb)

        
        if output.multi_face_landmarks:
            
            mp.solutions.drawing_utils.draw_landmarks(
                image=frame,
                landmark_list=output.multi_face_landmarks[0],
                connections=fm.FACEMESH_TESSELATION,
                landmark_drawing_spec=None,
                connection_drawing_spec=mp.solutions.drawing_styles.get_default_face_mesh_tesselation_style()
            )

            
            face = []
            for lm in output.multi_face_landmarks[0].landmark:
                face.extend([lm.x, lm.y, lm.z])
            face.append(name)
            final_data.append(face)
            sample_count += 1
            # print(f"Captured sample {sample_count}/{required_samples} for {name}")
            time.sleep(0.09)

        
        cv2.imshow("Face Registration", frame)

        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            print("Early quit.")
            vid.release()
            cv2.destroyAllWindows()
            exit()

    print(f"Finished capturing for '{name}'")


vid.release()
cv2.destroyAllWindows()

num_features = 478 * 3
columns = list(range(num_features)) + ['label']
df = pd.DataFrame(final_data, columns=columns)

# df.to_csv(r"C:\Users\Varshitha\Desktop\gifb ml\attendence_data.csv", index=False)
# print("\nData saved in numbered format to 'face_data_numbered.csv'")

How many faces to register?  8

Enter name for person 1:  snehith



Capturing 300 samples for 'snehith' in 3 seconds...
Finished capturing for 'snehith'



Enter name for person 2:  varshitha



Capturing 300 samples for 'varshitha' in 3 seconds...
Finished capturing for 'varshitha'



Enter name for person 3:  bhagyasri



Capturing 300 samples for 'bhagyasri' in 3 seconds...
Finished capturing for 'bhagyasri'



Enter name for person 4:  archana



Capturing 300 samples for 'archana' in 3 seconds...
Finished capturing for 'archana'



Enter name for person 5:  madhavi



Capturing 300 samples for 'madhavi' in 3 seconds...
Finished capturing for 'madhavi'



Enter name for person 6:  sravani



Capturing 300 samples for 'sravani' in 3 seconds...
Finished capturing for 'sravani'



Enter name for person 7:  nikitha



Capturing 300 samples for 'nikitha' in 3 seconds...
Finished capturing for 'nikitha'



Enter name for person 8:  kalyani



Capturing 300 samples for 'kalyani' in 3 seconds...
Finished capturing for 'kalyani'


In [2]:
df.to_csv(r"C:\Users\Varshitha\Desktop\gifb ml\attendence_data.csv", index=False)
print("\nData saved in numbered format to 'face_data_numbered.csv'")


Data saved in numbered format to 'face_data_numbered.csv'


In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv(r"C:\Users\Varshitha\Desktop\gifb ml\attendence_data_f.csv")

In [3]:
df.shape

(3200, 1435)

In [4]:
df

0         1         2         3         4         5         6  \
0     0.476772  0.590401 -0.043029  0.475780  0.509971 -0.085611  0.480132   
1     0.469036  0.594605 -0.043607  0.467557  0.511115 -0.084462  0.473042   
2     0.469552  0.594462 -0.044067  0.467872  0.511029 -0.085168  0.473242   
3     0.470099  0.594085 -0.044085  0.467839  0.511377 -0.085279  0.473260   
4     0.469714  0.594369 -0.043970  0.468089  0.511695 -0.085165  0.473370   
...        ...       ...       ...       ...       ...       ...       ...   
3195  0.559845  0.638781 -0.062070  0.577803  0.535770 -0.104666  0.566416   
3196  0.560641  0.638374 -0.061851  0.577377  0.536562 -0.104788  0.565990   
3197  0.561349  0.641659 -0.062302  0.579987  0.534820 -0.104645  0.568458   
3198  0.561223  0.640552 -0.062027  0.579592  0.537346 -0.104422  0.568130   
3199  0.570050  0.645419 -0.061923  0.585994  0.540271 -0.104845  0.574418   

             7         8         9  ...      1425      1426      1427  \
0     0.533041 -0.046135  0.470880  ...  0.590962  0.347934 -0.004543   
1     0.535485 -0.045545  0.462337  ...  0.586716  0.347750 -0.005460   
2     0.535456 -0.046055  0.462439  ...  0.584690  0.347914 -0.005329   
3     0.535581 -0.046035  0.462463  ...  0.584682  0.347992 -0.005626   
4     0.535955 -0.045915  0.462678  ...  0.584799  0.348011 -0.005457   
...        ...       ...       ...  ...       ...       ...       ...   
3195  0.567722 -0.059033  0.551477  ...  0.636652  0.371542  0.054937   
3196  0.568329 -0.059028  0.551042  ...  0.636676  0.371109  0.054441   
3197  0.567382 -0.059236  0.553633  ...  0.638470  0.374010  0.054964   
3198  0.569435 -0.059000  0.553304  ...  0.638281  0.373019  0.054940   
3199  0.572738 -0.058961  0.560436  ...  0.644321  0.378177  0.054364   

          1428      1429      1430      1431      1432      1433    label  
0     0.574307  0.365112 -0.004543  0.589891  0.385502 -0.004543  snehith  
1     0.569330  0.365283 -0.005460  0.585565  0.386071 -0.005460  snehith  
2     0.567256  0.365715 -0.005329  0.583363  0.386762 -0.005329  snehith  
3     0.567209  0.365887 -0.005626  0.583376  0.387026 -0.005626  snehith  
4     0.567410  0.365941 -0.005457  0.583501  0.387092 -0.005457  snehith  
...        ...       ...       ...       ...       ...       ...      ...  
3195  0.616707  0.392936  0.054937  0.635855  0.416400  0.054937  kalyani  
3196  0.616479  0.392718  0.054441  0.635848  0.416445  0.054441  kalyani  
3197  0.619757  0.394642  0.054964  0.637693  0.416871  0.054964  kalyani  
3198  0.618156  0.394377  0.054940  0.637350  0.418014  0.054940  kalyani  
3199  0.626109  0.398793  0.054364  0.643681  0.420597  0.054364  kalyani  

[3200 rows x 1435 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Columns: 1435 entries, 0 to label
dtypes: float64(1434), object(1)
memory usage: 35.0+ MB


In [6]:
df.dropna(inplace=True)

In [7]:
fv= df.iloc[:,:-1]
cv=df.iloc[:,-1]

In [8]:
cv.shape

(3200,)

In [9]:
fv.shape

(3200, 1434)

In [10]:
fv.values

array([[ 0.4767715 ,  0.5904007 , -0.04302905, ...,  0.58989149,
         0.38550249, -0.00454346],
       [ 0.46903637,  0.59460539, -0.04360721, ...,  0.58556455,
         0.38607088, -0.00545997],
       [ 0.46955156,  0.59446234, -0.04406699, ...,  0.58336282,
         0.38676196, -0.00532864],
       ...,
       [ 0.56134897,  0.6416586 , -0.06230197, ...,  0.63769287,
         0.41687128,  0.05496365],
       [ 0.56122327,  0.64055192, -0.06202695, ...,  0.63735044,
         0.41801351,  0.05494035],
       [ 0.57004976,  0.645419  , -0.06192263, ...,  0.64368057,
         0.42059711,  0.05436438]])

In [11]:
final_preprocessing_data = []

for d1 in fv.values:
    md = d1.reshape(478, 3)
    center = md - md[1]  
    distance = np.linalg.norm(md[33] - md[263]) 
    fpd = center / distance
    final_preprocessing_data.append(fpd.flatten())

In [12]:
final_preprocessing_data

[array([ 0.00451888,  0.36669182,  0.19413896, ...,  0.52025111,
        -0.56747207,  0.36960096]),
 array([ 0.00679137,  0.38327451,  0.18755208, ...,  0.54173336,
        -0.5740378 ,  0.36267331]),
 array([ 0.00772309,  0.38368196,  0.1890084 , ...,  0.53110258,
        -0.57146185,  0.36715301]),
 array([ 0.0103725 ,  0.37955317,  0.1890422 , ...,  0.53020811,
        -0.57065022,  0.36553067]),
 array([ 0.00747816,  0.38063119,  0.18966221, ...,  0.53136004,
        -0.57367976,  0.36697896]),
 array([ 0.00877278,  0.37763428,  0.18946941, ...,  0.52869922,
        -0.57100843,  0.36484664]),
 array([ 0.00632111,  0.38138501,  0.1897335 , ...,  0.52720785,
        -0.57184454,  0.36547142]),
 array([ 0.00800067,  0.38009889,  0.190109  , ...,  0.52682547,
        -0.57104478,  0.36442208]),
 array([ 0.00739149,  0.37867853,  0.19013833, ...,  0.52604739,
        -0.5703064 ,  0.36450088]),
 array([ 0.00723565,  0.3783872 ,  0.1900604 , ...,  0.5255429 ,
        -0.56954039,  0.36

In [13]:
pd.DataFrame(final_preprocessing_data).shape

(3200, 1434)

In [14]:
df['label'].value_counts()

label
snehith      400
varshitha    400
bhagyasri    400
archana      400
madhavi      400
sravani      400
nikitha      400
kalyani      400
Name: count, dtype: int64

In [15]:
import sklearn

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf = RandomForestClassifier(n_estimators=10)

In [18]:
rf.fit(final_preprocessing_data,cv)

RandomForestClassifier(n_estimators=10)

In [ ]:
import cv2
import mediapipe as mp
import time
import pandas as pd
import numpy as np


vid=cv2.VideoCapture(0)
fm=mp.solutions.face_mesh
model=fm.FaceMesh(
    static_image_mode=False,
    max_num_faces=5,
    refine_landmarks=True,
    min_detection_confidence=0.8,
    min_tracking_confidence=0.8)


vid = cv2.VideoCapture(0)
final_data=[]


while True:
    s,frames=vid.read() 
    if s==False:
        break
    frgb=cv2.cvtColor(frames,cv2.COLOR_BGR2RGB)
    
    output=model.process(frgb)
    
    if output.multi_face_landmarks:
        mp.solutions.drawing_utils.draw_landmarks(image=frames,landmark_list=output.multi_face_landmarks[0],connections=fm.FACEMESH_TESSELATION,
                                             landmark_drawing_spec=None,
                                              connection_drawing_spec=mp.solutions.drawing_styles.get_default_face_mesh_tesselation_style())
        cv2.imshow("face",frames)
        
        if cv2.waitKey(1) & 255== ord("q"):
            break

        face=[]
        if cv2.waitKey(1) & 255== ord("s"):
            if output.multi_face_landmarks:
                for i in output.multi_face_landmarks[0].landmark:
                    face.append(i.x)
                    face.append(i.y)
                    face.append(i.z)
            
        if bool(face)!=False:
            no_face = []
            f1 = np.array(face).reshape(478,3)
            center = f1-f1[1]
            distance=np.linalg.norm(f1[33]-f1[263])
            fpd = center/distance
            no_face.append(fpd.flatten())
            prediction=rf.predict(no_face)

            print("login successfully done {}".format(prediction[0]))
            print("login time for {} captured : ".format(prediction[0]),time.ctime())
    
cv2.destroyAllWindows()

login successfully done varshitha
login time for varshitha captured :  Tue Jul  1 15:33:13 2025
login successfully done varshitha
login time for varshitha captured :  Tue Jul  1 15:33:13 2025
login successfully done bhagyasri
login time for bhagyasri captured :  Tue Jul  1 15:33:22 2025
login successfully done nikitha
login time for nikitha captured :  Tue Jul  1 15:33:22 2025
login successfully done snehith
login time for snehith captured :  Tue Jul  1 15:33:32 2025
login successfully done snehith
login time for snehith captured :  Tue Jul  1 15:33:33 2025
login successfully done archana
login time for archana captured :  Tue Jul  1 15:33:40 2025
login successfully done archana
login time for archana captured :  Tue Jul  1 15:33:43 2025
login successfully done madhavi
login time for madhavi captured :  Tue Jul  1 15:33:49 2025
login successfully done sravani
login time for sravani captured :  Tue Jul  1 15:34:01 2025
login successfully done sravani
login time for sravani captured :  T

In [ ]:
import os
import cv2
import time
import pickle
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
import mediapipe as mp
import optuna
from optuna.samplers import GridSampler


class FaceAttendanceSystem:
    def _init_(self):
        self.SAMPLES = 150
        self.TIMEOUT_SECONDS = 10
        self.CAMERA_INDEX = 0
        self.face_data_file = "attendance_users_data.csv"
        self.attendance_file = "attendance_log_records.csv"
        self.model_file = "trained_face_model.pkl"
        self.features_file = "landmark_features.pkl"
        self.active_users = {}
        self.login_times = {}
        self.model = None
        self.features = None

        self.drawing_spec = mp.solutions.drawing_utils.DrawingSpec(thickness=1, circle_radius=1)
        self.face_mesh = mp.solutions.face_mesh.FaceMesh(
            static_image_mode=False,
            max_num_faces=1,
            refine_landmarks=True,
            min_detection_confidence=0.8,
            min_tracking_confidence=0.8
        )

        if not os.path.exists(self.attendance_file):
            pd.DataFrame(columns=['Name', 'Login Time', 'Logout Time', 'Duration']).to_csv(self.attendance_file, index=False)

        self.load_model()

    def preprocess(self, landmarks):
        face = np.array([[lm.x, lm.y, lm.z] for lm in landmarks])
        centered = face - face[1]
        distance = np.linalg.norm(face[33] - face[263])
        normalized = centered / distance
        return normalized.flatten()

    def register_user(self, name):
        cap = cv2.VideoCapture(self.CAMERA_INDEX)
        collected_data = []
        sample_count = 0
        print(f"[INFO] Registering: {name}")
        time.sleep(2)

        while sample_count < self.SAMPLES:
            ret, frame = cap.read()
            if not ret:
                continue
            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            result = self.face_mesh.process(rgb)
            if result.multi_face_landmarks:
                landmarks = result.multi_face_landmarks[0].landmark
                vector = self.preprocess(landmarks).tolist()
                vector.append(name)
                collected_data.append(vector)
                sample_count += 1

                mp.solutions.drawing_utils.draw_landmarks(
                    frame, result.multi_face_landmarks[0],
                    mp.solutions.face_mesh.FACEMESH_TESSELATION,
                    self.drawing_spec, self.drawing_spec
                )
                cv2.putText(frame, f"{name}: {sample_count}/{self.SAMPLES}", (10, 30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
            cv2.imshow("Registering New User", frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        cap.release()
        cv2.destroyAllWindows()

        if collected_data:
            columns = list(range(len(collected_data[0]) - 1)) + ['label']
            df = pd.DataFrame(collected_data, columns=columns)
            if os.path.exists(self.face_data_file):
                df.to_csv(self.face_data_file, mode='a', header=False, index=False)
            else:
                df.to_csv(self.face_data_file, index=False)
            self.train_model()
            print(f"[SUCCESS] {name} registered successfully.")
        else:
            print("[ERROR] No data collected.")

    def train_model(self):
        df = pd.read_csv(self.face_data_file)
        X = df.drop('label', axis=1)
        y = df['label']
        self.features = X.columns.tolist()

        search_space = {
            'n_estimators': [50, 100, 150],
            'max_depth': [None, 10, 20],
            'min_samples_split': [2, 5],
            'min_samples_leaf': [1, 2]
        }
        sampler = GridSampler(search_space)

        def objective(trial):
            params = {
                'n_estimators': trial.suggest_categorical('n_estimators', search_space['n_estimators']),
                'max_depth': trial.suggest_categorical('max_depth', search_space['max_depth']),
                'min_samples_split': trial.suggest_categorical('min_samples_split', search_space['min_samples_split']),
                'min_samples_leaf': trial.suggest_categorical('min_samples_leaf', search_space['min_samples_leaf'])
            }
            model = RandomForestClassifier(**params, random_state=42)
            scores = cross_val_score(model, X, y, cv=3, scoring='accuracy')
            return scores.mean()

        study = optuna.create_study(direction='maximize', sampler=sampler)
        study.optimize(objective, n_trials=len(sampler._all_grids))

        print("[OPTUNA] Best params:", study.best_params)
        print("[OPTUNA] Best accuracy:", study.best_value)

        best_params = study.best_params
        self.model = RandomForestClassifier(**best_params, random_state=42)
        self.model.fit(X, y)

        pickle.dump(self.model, open(self.model_file, 'wb'))
        pickle.dump(self.features, open(self.features_file, 'wb'))

    def load_model(self):
        if os.path.exists(self.model_file) and os.path.exists(self.features_file):
            self.model = pickle.load(open(self.model_file, 'rb'))
            self.features = pickle.load(open(self.features_file, 'rb'))

    def update_attendance_log(self, name, login_time, logout_time):
        duration = logout_time - login_time
        df = pd.read_csv(self.attendance_file)

        if 'Logout Time' not in df.columns:
            df['Logout Time'] = ''
        if 'Duration' not in df.columns:
            df['Duration'] = ''

        df['Logout Time'] = df['Logout Time'].fillna('')
        df['Duration'] = df['Duration'].astype(str)

        mask = (df['Name'] == name) & (df['Logout Time'] == '')
        df.loc[mask, 'Logout Time'] = logout_time.strftime("%Y-%m-%d %H:%M:%S")
        df.loc[mask, 'Duration'] = str(duration)

        df.to_csv(self.attendance_file, index=False)
        print(f"[LOGOUT] {name} at {logout_time.strftime('%H:%M:%S')} | Duration: {duration}")

    def mark_login(self, name, current_time):
        self.active_users[name] = current_time
        self.login_times[name] = current_time

        df = pd.read_csv(self.attendance_file)
        new_entry = pd.DataFrame([{
            'Name': name,
            'Login Time': current_time.strftime("%Y-%m-%d %H:%M:%S"),
            'Logout Time': '',
            'Duration': ''
        }])
        df = pd.concat([df, new_entry], ignore_index=True)
        df.to_csv(self.attendance_file, index=False)
        print(f"[LOGIN] {name} at {current_time.strftime('%H:%M:%S')}")

    def start_attendance(self):
        if self.model is None or self.features is None:
            name = input("No users found. Enter name to register: ")
            self.register_user(name)
            self.load_model()

        cap = cv2.VideoCapture(self.CAMERA_INDEX)
        print("[INFO] Attendance system started. Press 'q' to quit.")

        while True:
            ret, frame = cap.read()
            if not ret:
                continue

            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            result = self.face_mesh.process(rgb)
            now = datetime.now()

            if result.multi_face_landmarks:
                landmarks = result.multi_face_landmarks[0].landmark
                vector = self.preprocess(landmarks)
                X = pd.DataFrame([vector], columns=self.features)

                try:
                    probs = self.model.predict_proba(X)[0]
                    max_prob = np.max(probs)
                    name = self.model.classes_[np.argmax(probs)]
                except:
                    max_prob = 0
                    name = None

                if max_prob < 0.7:
                    cv2.putText(frame, "New Face Detected. Registering...", (10, 30),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
                    cv2.imshow("Face Attendance - Mesh View", frame)
                    cv2.waitKey(1)
                    cap.release()
                    cv2.destroyAllWindows()
                    entered_name = input("[INPUT] Enter name for new user: ")
                    self.register_user(entered_name)
                    self.load_model()
                    cap = cv2.VideoCapture(self.CAMERA_INDEX)
                    continue
                else:
                    if name not in self.active_users:
                        self.mark_login(name, now)
                    else:
                        self.active_users[name] = now

                    mp.solutions.drawing_utils.draw_landmarks(
                        frame, result.multi_face_landmarks[0],
                        mp.solutions.face_mesh.FACEMESH_TESSELATION,
                        self.drawing_spec, self.drawing_spec
                    )
                    cv2.putText(frame, f"{name} Detected", (20, 40),
                                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

            for user in list(self.active_users.keys()):
                if (now - self.active_users[user]).total_seconds() > self.TIMEOUT_SECONDS:
                    logout_time = now
                    login_time = self.login_times[user]
                    self.update_attendance_log(user, login_time, logout_time)
                    del self.active_users[user]
                    del self.login_times[user]

            cv2.imshow("Face Attendance - Mesh View", frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        now = datetime.now()
        for user in list(self.active_users.keys()):
            login_time = self.login_times[user]
            self.update_attendance_log(user, login_time, now)
            print(f"[FORCED LOGOUT] {user} at {now.strftime('%H:%M:%S')} | Duration: {now - login_time}")
        cap.release()
        cv2.destroyAllWindows()


if _name_ == "_main_":
    system = FaceAttendanceSystem()
    system.start_attendance()